Traceback (most recent call last):
  File "/Users/mikaelmortensen/opt/anaconda3/envs/bookmatmek4270/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/mikaelmortensen/opt/anaconda3/envs/bookmatmek4270/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/mikaelmortensen/opt/anaconda3/envs/bookmatmek4270/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/mikaelmortensen/opt/anaconda3/envs/bookmatmek4270/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/mikaelmortensen/opt/anaconda3/envs/bookmatmek4270/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/mikaelmortensen/opt/anaconda3/envs/bookmatmek4270/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/mikaelmortensen/opt/anaconda3/envs/bookmatmek4270/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
xij, yij, data = solver(40, 1, 501, cfl=0.5, store_data=5)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mUnboundLocalError[0m                         Traceback (most recent call last)
Cell [0;32mIn[35], line 1[0m
[0;32m----> 1[0m xij, yij, data [38;5;241m=[39m [43msolver[49m[43m([49m[38;5;241;43m40[39;49m[43m,[49m[43m [49m[38;5;241;43m1[39;49m[43m,[49m[43m [49m[38;5;241;43m501[39;49m[43m,[49m[43m [49m[43mcfl[49m[38;5;241;43m=[39;49m[38;5;241;43m0.5[39;49m[43m,[49m[43m [49m[43mstore_data[49m[38;5;241;43m=[39;49m[38;5;241;43m5[39;49m[43m)[49m

Cell [0;32mIn[34], line 6[0m, in [0;36msolver[0;34m(N, L, Nt, cfl, c, store_data, u0)[0m
[1;32m      4[0m Unp1, Un, Unm1 [38;5;241m=[39m np[38;5;241m.[39mzeros(([38;5;241m3[39m, N[38;5;241m+[39m[38;5;241m1[39m, N[38;5;241m+[39m[38;5;241m1[39m))
[1;32m      5[0m Unm1[:] [38;5;241m=[39m u0(xij, yij)
[0;32m----> 6[0m Un[:] [38;5;241m=[39m Unm1[:] [38;5;241m+[39m [38;5;241m0.5[39m[38;5;241m*[39m(c[38;5;241m*[39m[43mdt[49m)[38;5;241m*[39m[38;5;241m*[39m[38;5;241m2[39m[38;5;241m*[39m(D [38;5;241m@[39m Un [38;5;241m+[39m Un [38;5;241m@[39m D[38;5;241m.[39mT)
[1;32m      7[0m dx [38;5;241m=[39m L [38;5;241m/[39m N
[1;32m      8[0m D [38;5;241m=[39m D2(N)[38;5;241m/[39mdx[38;5;241m*[39m[38;5;241m*[39m[38;5;241m2[39m

[0;31mUnboundLocalError[0m: local variable 'dt' referenced before assignment

